name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      skip-tests:
        description: 'Skip tests'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: |
        if [ "${{ github.event.inputs.skip-tests }}" = "true" ]; then
          mvn -B clean package -DskipTests --file pom.xml
        else
          mvn -B clean package --file pom.xml
        fi
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FinancialTracker
        path: target/FinancialTracker-*.jar
